00_vecadd: 00_vecadd.cpp
	g++ 00_vecadd.cpp -fopt-info-vec-optimized -march=native -O3
01_reduction: 01_reduction.cpp
	g++ 01_reduction.cpp -fopt-info-vec-optimized -march=native -O3
02_if: 02_if.cpp
	g++ 02_if.cpp -fopt-info-vec-optimized -march=native -O3
03_function: 03_function.cpp
	g++ 03_function.cpp -fopt-info-vec-optimized -march=native -O3
04_permute: 04_permute.cpp
	g++ 04_permute.cpp -fopt-info-vec-optimized -march=native -O3
05_sin: 05_sin.cpp
	g++ 05_sin.cpp -fopt-info-vec-optimized -march=native -O3
06_intrinsic_vecadd: 06_intrinsic_vecadd.cpp
	g++ 06_intrinsic_vecadd.cpp -march=native -O3
07_intrinsic_reduction: 07_intrinsic_reduction.cpp
	g++ 07_intrinsic_reduction.cpp -march=native -O3
08_intrinsic_if: 08_intrinsic_if.cpp
	g++ 08_intrinsic_if.cpp -march=native -O3
09_intrinsic_permute: 09_intrinsic_permute.cpp
	g++ 09_intrinsic_permute.cpp -march=native -O3
10_intrinsic_sin: 10_intrinsic_sin.cpp
	icc 10_intrinsic_sin.cpp -xHost
11_nbody: 11_nbody.cpp
	g++ 11_nbody.cpp -march=native -O3
