00_hello: 00_hello.cpp
	g++ 00_hello.cpp -fopenmp
01_num_threads: 01_num_threads.cpp
	g++ 01_num_threads.cpp -fopenmp
02_loop: 02_loop.cpp
	g++ 02_loop.cpp -fopenmp
03_iterator: 03_iterator.cpp
	g++ 03_iterator.cpp -fopenmp
04_scope: 04_scope.cpp
	g++ 04_scope.cpp -fopenmp
05_scope: 05_scope.cpp 05_bar.cpp
	g++ 05_scope.cpp 05_bar.cpp -fopenmp
06_sections: 06_sections.cpp
	g++ 06_sections.cpp -fopenmp
07_private: 07_private.cpp
	g++ 07_private.cpp -fopenmp
08_tasks: 08_tasks.cpp
	g++ 08_tasks.cpp -fopenmp
09_reduction: 09_reduction.cpp
	g++ 09_reduction.cpp -fopenmp
10_atomic: 10_atomic.cpp
	g++ 10_atomic.cpp -fopenmp
11_scan: 11_scan.cpp
	g++ 11_scan.cpp -fopenmp
12_pi: 12_pi.cpp
	g++ 12_pi.cpp -fopenmp
13_merge_sort: 13_merge_sort.cpp
	g++ 13_merge_sort.cpp -fopenmp
14_bucket_sort: 14_bucket_sort.cpp
	g++ 14_bucket_sort.cpp -fopenmp
