00_write: 00_write.cpp
	g++ 00_write.cpp -O3
01_read: 01_read.cpp
	g++ 01_read.cpp -O3
02_binary_write: 02_binary_write.cpp
	g++ 02_binary_write.cpp -O3
03_binary_read: 03_binary_read.cpp
	g++ 03_binary_read.cpp -O3
04_mpi_write: 04_mpi_write.cpp
	mpicxx 04_mpi_write.cpp -O3
05_mpi_read: 05_mpi_read.cpp
	mpicxx 05_mpi_read.cpp -O3
06_mpi_io_write: 06_mpi_io_write.cpp
	mpicxx 06_mpi_io_write.cpp -O3
07_mpi_io_read: 07_mpi_io_read.cpp
	mpicxx 07_mpi_io_read.cpp -O3
08_mpi_io_write_view: 08_mpi_io_write_view.cpp
	mpicxx 08_mpi_io_write_view.cpp -O3
09_mpi_io_read_view: 09_mpi_io_read_view.cpp
	mpicxx 09_mpi_io_read_view.cpp -O3
10_mpi_io_write_all: 10_mpi_io_write_all.cpp
	mpicxx 10_mpi_io_write_all.cpp -O3
11_mpi_io_read_all: 11_mpi_io_read_all.cpp
	mpicxx 11_mpi_io_read_all.cpp -O3
12_derived_write: 12_derived_write.cpp
	mpicxx 12_derived_write.cpp -O3
13_derived_read: 13_derived_read.cpp
	mpicxx 13_derived_read.cpp -O3
14_hdf5_write: 14_hdf5_write.cpp
	g++ 14_hdf5_write.cpp -lhdf5
15_hdf5_read: 15_hdf5_read.cpp
	g++ 15_hdf5_read.cpp -lhdf5
16_phdf5_write: 16_phdf5_write.cpp
	mpicxx 16_phdf5_write.cpp -lhdf5
17_phdf5_read: 17_phdf5_read.cpp
	mpicxx 17_phdf5_read.cpp -lhdf5
